# Units of delay: milliseconds
minDelay: 1000
maxDelay: 10000

process:
  - id: 0
    ip: 127.0.0.1
    port: 10000
  - id: 1
    ip: 127.0.0.1
    port: 10001
  - id: 2
    ip: 127.0.0.1
    port: 10002
  - id: 3
    ip: 127.0.0.1
    port: 10003
  - id: 4
    ip: 127.0.0.1
    port: 10004